### ISSUE TITLE
No license error on upgrade

### ISSUE THREAD

**Issue by artigat1** [mbolotov/intellij-cypress#106]
I've upgraded to the latest version of Rider `JetBrains Rider 2022.2.3` and upgraded to the latest Cypress Plugin. Before the plugin upgrade, it said my license was valid until April 2023, but now it says there is no license. Can I downgrade again? I use this all the time in my day-to-day work, but it won't start or do anything now.

![image](https://user-images.githubusercontent.com/1673835/195039226-ff9d3a01-2b25-4343-b439-673c1459a967.png)

**Comment by dianawieczorek** [comment]
Nothing works.

**Comment by mbolotov** [comment]
@dianawieczorek 
What does the `Register` window show for the `Cypress Support Pro` plugin?
You've entered the license there and the plugin still shown with `No license`?

**Comment by dianawieczorek** [comment]
ok I downgrade cypress and it works

**Comment by artigat1** [comment]
I tried a full IDE restart, I've even restarted the laptop a couple of times since the updates were installed. I'm still getting the same thing. 

I uninstalled and re-installed the Cypress plugin, but got the same thing happen. 

Without thinking, I upgraded on my other laptop and I get the same thing on both laptops now and can't see how to roll anything back.

**Comment by mbolotov** [comment]
@artigat1 
The same question for you:

What does the `Register` window show for the `Cypress Support Pro` plugin?
You've entered the license there and the plugin is still shown with `No license`?

**Comment by mbolotov** [comment]
this seems to be some misconfiguration / platform issue. 
the marketplace shows that the plugin do support other platforms as well:
![image](https://user-images.githubusercontent.com/19785715/195340145-fcb77ac9-c577-456f-a515-60e4a18f2b23.png)
I asked help from the JetBrains team.

**Comment by mbolotov** [comment]
can you try this bundle:
[Cypress Support Pro-3.4.1-EAP.zip](https://github.com/mbolotov/intellij-cypress/files/9764772/Cypress.Support.Pro-3.4.1-EAP.zip)

**Comment by artigat1** [comment]
That has worked. Thank you very much.

**Comment by mbolotov** [comment]
should be fixed in 3.4.1
