### ISSUE TITLE
Webstorm Support is Missing

### ISSUE THREAD

**Issue by fmquaglia** [mbolotov/intellij-cypress#108]
I just updated the plugin to 3.4 in Webstorm.
Now I can't use the plugin anymore.

<img width="1309" alt="Preferences 2022-10-13 at 2 26 30 PM" src="https://user-images.githubusercontent.com/678453/195665041-4f605ba5-7db6-4b88-997f-b0e7eac509f4.png">

I tried uninstalling and reinstalling but got this error toast:

<img width="416" alt="walden – MultipleOwners spec js 2022-10-13 at 2 32 07 PM" src="https://user-images.githubusercontent.com/678453/195666065-7d1eb2fd-20ef-44e6-9ea6-ec731c772194.png">

Rolled back to 3.3.1, downloading it from the [plugin's page](https://plugins.jetbrains.com/plugin/13987-cypress-support-pro/versions) and it worked again.

<img width="1024" alt="Preferences 2022-10-13 at 2 45 05 PM" src="https://user-images.githubusercontent.com/678453/195668421-4ffd96f8-a5ce-4d2d-8574-b10a20fb0de4.png">

**Versions**:
- Plugin: 3.4
- IDE: WebStorm 2022.2.2 Build #WS-222.4167.31, built on September 14, 2022
- OS: macOS 12.6

**Comment by mbolotov** [comment]
Yes, this is a know problem.
We will release a new version with the fix soon. Meanwhile, you can manually install this bundle:
[Cypress Support Pro-3.4.1-EAP.zip](https://github.com/mbolotov/intellij-cypress/files/9780786/Cypress.Support.Pro-3.4.1-EAP.zip)

**Comment by mbolotov** [comment]
should be fixed in 3.4.1

**Comment by fmquaglia** [comment]
testing now, thanks
