### ISSUE TITLE
cypress pro support opens additional chrome tab on test execution

### ISSUE THREAD

**Issue by pitoniak** [mbolotov/intellij-cypress#109]
upon defining a run config and executing it the chrome browser opens an additional tab displaying the virtru home page...
**Versions**:
- Plugin: latest build
- IDE: webstorm
- OS: mac
is it possible there is some cache that needs to be cleared on the browser user by the plugin? other tan that it appears to work nicely.

thx

**Comment by mbolotov** [comment]
Could you try running the same setup from the command line to see if it can be reproduced without the plugin?
I suspect there is nothing can be done at the plugin side.

**Comment by pitoniak** [comment]
it does in fact also happen when i copy the command file generated by the plugin and run it on te command line...odd.
thx for response...love the ability to debug from webstrorm...great work!

**Comment by mbolotov** [comment]
thanks!
so can we close this issue?

**Comment by mbolotov** [comment]
closing as nothing can be done on the plugin side
