### ISSUE TITLE
Debugger on Pro Version does not stop on my breakpoints

### ISSUE THREAD

**Issue by Gardosen** [mbolotov/intellij-cypress#113]
**Describe the bug**
I am using the pro version of your plugin to be able to debug my code. 
I am using Cypress with Cucumber and Gherkin. 

using the code line "debugger" inside the code, works.
I also tested the test project you provided and it works for me. 

But on my project for some reason, the breakpoints inside my JS code are not recognized.

Please help me :( It worked once like 10 Months ago, but i do not know what has changed since then.... I am really lost right now.

**Versions**:
- Plugin: Cypress Support PRO
- IDE: WebStorm 2022.2.4
- OS: MacOS Monterey
- Example project: https://github.com/Gardosen/automation-test/

**Comment by Gardosen** [comment]
@mbolotov can you help me? :(

**Comment by mbolotov** [comment]
Hi Marco,
I had a look into it and was able to reproduce the problem. However, I currently have no idea what's wrong and how it can be fixed. 
I will try to investigate this issue sometime later.

**Comment by Gardosen** [comment]
okay, i remember when it was working for me, i had cypress 9, i wonder if anything changed in between, which broke the compatibility. 

i will also make some tests with cypress 9 and my current codebase, maybe i find something which helps us nailing the issue down :)

**Comment by Gardosen** [comment]
@mbolotov I fixed the issue, i am not good enought to understand and dig into the cause of the issue. but i can tell that it is the esbuild-preprocessor plugin.

i replaced it now with the browserify preprocessor and the ide is stopping correctly on the breakpoints when using chrome. 

I do not know if this helps you, but can it be that for cucumber with gherkin and your plugin it is necessary to use browserify and not esbuild as a preprocessor? or was i just lucky to fix it?

you can find the change i did to make it work in this branch on my example project
https://github.com/Gardosen/automation-test/compare/main...cypress-support-pro-fix

i changed nothing, except what you see in the commit.

Kind regards
Marco

**Comment by mbolotov** [comment]
Hi Marco!
Thanks for this finding. I suspect your project with esbuild has a problem with generation of source maps. And debugger cannot stop on a breakpoint when no source map is present. This applies not only to the plugin's debugger, but also to any other one. For instance, the dev tools debugger in Chrome won't stop as well.
Can we close this issue now?

**Comment by Gardosen** [comment]
Yes, we can :)
