### ISSUE TITLE
Cypress Pro Plugin not compatible with WebStorm EAP 2023.1

### ISSUE THREAD

**Issue by artmontesinos** [mbolotov/intellij-cypress#115]
Plugin page states:  **Incompatible requires IDE build 223.* or earlier**

**Comment by mbolotov** [comment]
I've released the 3.6.1 version with the `2023.1` support. While it's awaiting for the JB approval, you can use this bundle: 
[Cypress Support Pro-3.6.1.zip](https://github.com/mbolotov/intellij-cypress/files/10556018/Cypress.Support.Pro-3.6.1.zip)

**Comment by mbolotov** [comment]
fixed in 3.6.1
