### ISSUE TITLE
Unable to run spec typescript test file

### ISSUE THREAD

**Issue by kubecloudsinc** [mbolotov/intellij-cypress#117]
**Describe the bug**
  When the test file(spec file) is a typescript file with .ts extension, then not able to run and the plugin displays error "unable to run the test file"
  How do we run spec files or config files which are typescript?
  attached the screen shots 

**Versions**:  3.6
- Plugin:  Cypress Support Pro 
- IDE: WebStorm
- OS: Windows
![Screenshot 2023-03-08 143910](https://user-images.githubusercontent.com/66754241/223826192-5be68097-6f6a-454c-a0c2-a40b375446ac.png)
![Screenshot 2023-03-08 143316](https://user-images.githubusercontent.com/66754241/223826194-eca69ec0-25c2-49c6-ad78-f2726d7c0dd9.png)

**Comment by mbolotov** [comment]
@kubecloudsinc 
The `Test name` field is empty in your run configuration. If you want to run whole spec file, please switch to the `Spec file` mode:
![image](https://user-images.githubusercontent.com/19785715/224060611-41595f60-1502-49f3-b13d-e01e3a281ca9.png)

**Comment by kubecloudsinc** [comment]
Thanks, that makes sense now. 
  Since I opened this request already want to ask for one more feature to the plugin. If you see that in the Program Arguments passing a -P option for selecting project. It would be good to have these options in the plugin to make it more usable for TypeScript projects with multiple projects in the same workspace.

**Comment by mbolotov** [comment]
> to have these options in the plugin 
I will consider this option, thanks!
