### ISSUE TITLE
Test framework quits unexpectedly

### ISSUE THREAD

**Issue by v4l3nt1n** [mbolotov/intellij-cypress#118]
Plugin Version: 3.6 (PRO)
Cypress: 12.7.0
PyCharm: 2022.3.3 (Professional Edition)
MacOS 11.6.1

Hello,

I'm facing this issue since yesterday and i'm not sure on how to fix it.
Test framework quits unexpectedly.
I tried with several baseUrls that i can confirm they work.
It was working like a charm.

![image](https://user-images.githubusercontent.com/3154303/224134759-39c98ffa-1c7b-49a9-a7dc-2d53375701ab.png)

![image](https://user-images.githubusercontent.com/3154303/224135571-efc5b181-6981-4ff3-a904-9a7d69f6d6d1.png)

Thank you very much for this tool.

**Comment by v4l3nt1n** [comment]
The error only occurs when debugging. If I run it works as expected.

**Comment by mbolotov** [comment]
Hi @v4l3nt1n 
Sorry for the late answer. 
I can't say much regarding the problem. It looks like the IDE debug driver tries to download some sources from the `spi3pl-tech.com` domain. Usually, it goes to the local host for that. 
Unfortunately, I can't say more without the sample project. Could you share it somehow?

**Comment by valen-spi3pl** [comment]
Hello, sorry for the late late reply...
I updated the IDE several times and the plugin started working again.
There are many IDE updates these times...

Thanks for the great work, you can close this issue.
