### ISSUE TITLE
Test run configurations not available form the IntelliJ context menus

### ISSUE THREAD

**Issue by e-arroyo** [mbolotov/intellij-cypress#119]
I am using the Pro version in trial mode.

The context menus from the file-view or code-view do not show the cypress options. It assumes Mocha. This is cumbersome because the only way to run a Cypress test is by manually creating a new configuration whenever I want to run a test.

**IntelliJ Version**
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021

**Cypress Support Pro**
mbolotov 2.5.1

**System**
Apple M1
macOS Ventura 13.2.1

**Comment by mbolotov** [comment]
Are you sure about 2.5.1 version of the plugin? The current version is 3.6.1.
Anyway, it would be nice to have a sample project to reproduce the issue. Can you provide it?
If not, can you [collect the debug log data](https://github.com/mbolotov/intellij-cypress/issues/104#issuecomment-1247041722) and send it to me?

**Comment by e-arroyo** [comment]
I have updated my IntelliJ to version
2022.3.3

Also updated the plug-in yo version;
3.6

That did not fix anything. I still can’t get the context menus and I also noticed that the CY code completion doesn’t work either.

My project is extremely simple, I’m testing the plug-in either the tests generated by Cypress UI when initializing a new project.

Please advise if there is smithing else I can try. I really would like to get this to work before my trial period expires.


Sent from my iPhone

On Mar 11, 2023, at 1:24 AM, Mikhail Bolotov ***@***.***> wrote:

﻿

Are you sure about 2.5.1 version of the plugin? The current version is 3.6.1.
Anyway, it would be nice to have a sample project to reproduce the issue. Can you provide it?
If not, can you collect the debug log data<https://github.com/mbolotov/intellij-cypress/issues/104#issuecomment-1247041722> and send it to me?

**Comment by mbolotov** [comment]
Please check the if the plugin is enabled.
It may be deactivated due to several reasons:
![image](https://user-images.githubusercontent.com/19785715/224503954-30845586-ca4e-4d79-9cc9-111715605f4e.png)

**Comment by kenparker** [comment]
I actuallj have the same problem. I have the base version 1.4.2

It looks like that the default for new configurations is Node and not Cypress

**Comment by mbolotov** [comment]
@kenparker, please provide a sample project to reproduce the problem

**Comment by kenparker** [comment]
> 

hier https://github.com/kenparker/CypressTest

**Comment by kenparker** [comment]
> it's still not a valid cypress project because it does not contain a cypress configuration file. as soon as I added it, the plugin started creating a valid run configuration.

thanks for your quick feedback.

I have a cypress.config.js file in the directory, looking like:
`const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});`

**Comment by kenparker** [comment]
> it's still not a valid cypress project because it does not contain a cypress configuration file. as soon as I added it, the plugin started creating a valid run configuration.

how is your config file looking like?
thanks

**Comment by mbolotov** [comment]
A default config that is automatically created when you run `npx cypress open` for the first time:
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});

```

**Comment by mbolotov** [comment]
@kenparker so can you create a cypress run configuration for a test now?

**Comment by kenparker** [comment]
Hi, I have uninstalled the plugin and then installed again and everything seems fine
Thanks for support

**Comment by mbolotov** [comment]
> everything seems fine

I'm glad to hear that.

**Comment by mbolotov** [comment]
@e-arroyo 
do you still experience the problem?

**Comment by e-arroyo** [comment]
Interestingly enough, without me doing anything, it just started working.

I don’t know what changed, I’m not sure if I installed any updates to either IntelliJ or the plug-in, but I’m happy that it’s working.

With this working I will be glad to buy the subscription once my trial ends.

Thanks for following up on my request.

Sent from my iPhone

On Mar 17, 2023, at 6:09 AM, Mikhail Bolotov ***@***.***> wrote:

﻿

@e-arroyo<https://github.com/e-arroyo>
do you still experience the problem?
