### ISSUE TITLE
The plugin can't parse destructured file importing

### ISSUE THREAD

**Issue by AlexanderTunick** [mbolotov/intellij-cypress#12]
```
const { getConfigValue,
    dashboard: { dashboardUrl }, // where dashboard is the name of a file
    common: { dataCampaigns } } = require('kk/utils'); // where common is the name of a file
```

it works perfectly, but the plugin just can't pick it up and quits unexpectedly

> Oops...we found an error preparing this test file:
> 
>   /Users/alexti/WebstormProjects/klits-js/cypress/integration/dashboard/accountSettings/tracking.spec.js
> 
> The error was:
> 
> Error: Cannot find module 'klly/utils' from '/Users/alrti/WebstormProjects/kly-autotests-js/cypress/integration/dashboard/accountSettings'
> 
> 
> This occurred while Cypress was compiling and bundling your test code. This is usually caused by:
> 
> - A missing file or dependency
> - A syntax error in the file or one of its dependencies
> 
> Fix the error in your code and re-run your tests.

**Comment by mbolotov** [comment]
Hi @AlexanderTunick!
Thanks for you report!
 A couple of questions:
1. To be on the safe side: can you run your case from command line and does it run smoothly then?
2. Could you try different package managers to run the case? Please also try 'no manager' option - just keep the combobox value empty:
![image](https://user-images.githubusercontent.com/19785715/89876308-28573480-dbc7-11ea-863b-ce47af4a7e15.png)

If those actions still do not clarify the root of the problem, could you please provide a sample of project to reproduce the problem?

**Comment by mbolotov** [comment]
Hi @AlexanderTunick!
Are you still experience the problem?

**Comment by mbolotov** [comment]
Closing this as unreproducible. 
Please fell free to reopen if you have more information.
