### ISSUE TITLE
Paid version not working

### ISSUE THREAD

**Issue by Bothees** [mbolotov/intellij-cypress#121]
**Cypress support Pro paid version not working**

Cypress support Pro version not working. Seeing error message Required  Plugin 'XPathView'  to be installed though the plugin is already installed.

**Versions**:
- Plugin: Cypress support Pro 3.6-2022.2
- IDE: WebStorm 2022.2.4
- OS: Windows 10

**Comment by Bothees** [comment]
![Screenshot (64)](https://user-images.githubusercontent.com/8228656/229922672-c394aab1-0f15-49cc-8f16-02a3da1d4bc0.png)

**Comment by mbolotov** [comment]
Hi Bothi!
the strange thing there is that it shows 'No license'. 
Can you check whether it will work if you resolve the issue with license?

**Comment by Bothees** [comment]
Hi,
I have uninstalled and installed the plugin, it is all good now. However no idea, why it didn't pick up the license after Webstorm updated to the latest version. Thanks for looking into it.
