### ISSUE TITLE
cypress support pro does not work with cucumber pre processor 17.1.1+

### ISSUE THREAD

**Issue by Gardosen** [mbolotov/intellij-cypress#122]
Current behavior
when using the version 17.1.1 or higher from cypress-cucumber-preprocessor, cypress-support pro is not able to debug the cypress execution anymore.

Desired behavior
when i want to debug the code with the help of cypress support pro, it should stop at the breakpoints i set.

Test code to reproduce
https://github.com/Gardosen/automation-test/
branch: main <-- broken one with version 17.1.1
branch: debugger-fix-up <--- working one with version 17.1.0

Versions
Cypress version: 12.17.4
Preprocessor version: 17.1.0 / 17.1.1
Node version: 20.4.0
###Additional Note:

I am also opened up a bug report on the side of cypress-cucumber-preprocessor from badeball that it can be evaluated if the issue might be on the side of the preprocessor. Link: https://github.com/badeball/cypress-cucumber-preprocessor/issues/1085

**Versions**:
- Plugin: 3.6.3
- IDE: IntelliJ / WebStorm / Aqua
- OS: MacOS Monterey 12.6.1

**Comment by mbolotov** [comment]
Hi Marco!
Do you mean it works okay with the previous version of `cypress-cucumber-preprocessor`?
Do you try to set a breakpoint inside js/ts code? or at a cucumber step itself?

Anyway, I have to say that the ownership of the Cypress Support Pro plugin has been transferred to JetBrains and I no longer may provide any updates for the plugin.

**Comment by Gardosen** [comment]
Hello,

thanks for the question:
i have set breakpoints in the codebase itself (javascript files, i honestly never tested if i can also set breakpoints in the cucumber code)

I made several tests as i first tought it is an issue with cypress 12.17.4, but noticed that the preprocessor is actually what causes the debugger to not kick in anymore.

with 17.1.0 it works perfectly fine.
with 17.1.1 the breakpoints are not triggered and the automation runs trought.

You can check out the example project i have mentioned and the branches. main is the one with the broken plugin. debugger-fix-up is the one where it works fine.

**Comment by mbolotov** [comment]
if the debugger does not stop on a breakpoint, it usually means the project performs any kind of source code transformation and does not generate a valid source mappings for this transformation.
