### ISSUE TITLE
Unable to use with cucumber cypress

### ISSUE THREAD

**Issue by deepziem** [mbolotov/intellij-cypress#13]
![image](https://user-images.githubusercontent.com/54252717/90318480-bb150d80-defe-11ea-8e5c-1c83a8b35cd0.png)

![image](https://user-images.githubusercontent.com/54252717/90318489-ce27dd80-defe-11ea-84a0-742b004e162e.png)

![image](https://user-images.githubusercontent.com/54252717/90318499-dc75f980-defe-11ea-80a1-47a7d98986a2.png)

![image](https://user-images.githubusercontent.com/54252717/90318559-4e4e4300-deff-11ea-96e2-be625bfcd9be.png)

4. How to debug cucumber tests ?
1. I try to do debug and it does not go into debug window. goes to run window in webstorm.
2. how to put breakpoints ? its extremely vague in your documentation and videos .. seriously very very difficult to understand. We need at-least basic steps
3. It does not stop at breakpoints ..

**Comment by mbolotov** [comment]
Hi @deepziem 

You are right, the plugin does not support cucumber files. So one neither can set breakpoints nor even create a run configuration using a scenario gutter. 

As for the questions 5,6,7 - are you asking about a cucumber case or a general (mocha) one?

**Comment by mbolotov** [comment]
I tried breakpoints on a [sample cypress-cucumber project](https://github.com/TheBrainFamily/cypress-cucumber-example.git
). 

And I was able to setup a breakpoint on a **JavaScript-code line** and got debugger stopped on a breakpoint:
![image](https://user-images.githubusercontent.com/19785715/90381269-cba3c000-e085-11ea-9598-628e50c8e09b.png)

**Comment by deepziem** [comment]
@mbolotov i am not generally able to set up debugger. I did not mean to debug cucumber lines but the cypress javascript only. Based on my settings shown in screenshot what am i doing wrong, when i run why is it not running?

**Comment by mbolotov** [comment]
The plugin does not use npm scripts at all.
For starting a single feature file, I used the following run configuration:
![image](https://user-images.githubusercontent.com/19785715/90398030-6fe73000-e0a1-11ea-8685-040e162908cd.png)

**Comment by deepziem** [comment]
Thanks .. I tried same .. but somehow something is wrong ..  it does not bring up the debug window just the run window as below .. any idea why?


![image](https://user-images.githubusercontent.com/54252717/90404738-cbe59080-e070-11ea-9a82-1f84da0d6b61.png)

**Comment by mbolotov** [comment]
> try to edit from debug window

I'm not sure I understand what do you mean. Could you show where do you do edit from debug window?

BTW, did you try to debug the sample project I mentioned? I think it will be good to know whether the problem lies in your specific project or not.

**Comment by deepziem** [comment]
![image](https://user-images.githubusercontent.com/54252717/90425180-56d48400-e08d-11ea-9397-7323a36624f0.png)

I tried sample project and latest intellij , latest nodejs .. same issue . Breakpoint does not stop

**Comment by mbolotov** [comment]
is it possible to record the video of how you run the debug?
also, you could try to add a `debugger` statement into the code instead of a breakpoint to check if it's the breakpoint hit problem only

**Comment by kumzme** [comment]
[Cypress_test.zip](https://github.com/mbolotov/intellij-cypress/files/5087997/Cypress_test.zip)

**Comment by kumzme** [comment]
Ive added a recording .. same effect with .debug() or .debugger statement literally.

**Comment by mbolotov** [comment]
Okay, I got it:
![image](https://user-images.githubusercontent.com/19785715/90479875-09612100-e138-11ea-9882-d4695f252cd9.png)
The debugger session indeed can't be established in your case. 
You can try to disable automatic browser page selection here:
![image](https://user-images.githubusercontent.com/19785715/90480226-9f954700-e138-11ea-9e5e-ce960bd5e575.png)
In this case, debugger will ask for the page to connect if there are many:
![image](https://user-images.githubusercontent.com/19785715/90480683-45e14c80-e139-11ea-8ae5-a615d5c73dfd.png)
There are a few problems with this approach:
1. You should know what page to select (or just iterate through all of them and find it out)
2. The window is a pop-up and will disappear if you click on anything outside
3. The execution is not paused while you are selecting. So you have to be fast to not miss you breakpoint (or add delays in the test code)
So you can try this and see if it will work this way. 
It could be the single page with the name other than 'about:blank' and it then should work with the checkbox deselected.
If you find several pages and the correct page name is not 'about:blank' but has a static name, you can define it in the run settings.

**Comment by kumzme** [comment]
Wow That's nice .. I am able to debug now .

I was thinking of recommending to capital one for my team .. Can you also kindly put in instructions for cucumber and also cypress similar way in readme.md and also 

Can you suggest a way to debug as a script like this pls ? I am sure there is a way .. by intercepting chrome in a debugger session .. 
"test": "cypress run --spec \"**/*.feature\" --headed",

**Comment by mbolotov** [comment]
It's nice to see you've eventually got it to work. 
How does the page url look like? Is it static?

As for debugging scripts, I will look into your request. I think it's doable.

**Comment by deepziem** [comment]
Buddy .. not sure how to answer you .. I really donno .. I barely managed to make it work.

Even now as I mentioned .. The window pops up once or twice .. then it goes away .. then it debugs when we debug second time .. it does for 2 3 runs and the popup comes again.. then it works again etc.

I tried to clear cache of intellij and. restart .. popup comes .. and then repeats for sure

**Comment by mbolotov** [comment]
yep, that's strange.
could you please make a screenshot of the popup next time it appears?

**Comment by deepziem** [comment]
hmm oklemme try

**Comment by kumzme** [comment]
Hi, It's just as previous screenshots. Just that it will pop up now and then .. tried a few different macs. So kindly see if you can make this smooth. Cypress debugging is making my life hell.

Also npm script debugging pls.

**Comment by mbolotov** [comment]
Hi @kumzme 
So what options does popup offer? Are they the same each time?

> It's just as previous screenshots
Unfortunately, I don't see any popup on your screenshots here. Could you please attach one more?

**Comment by kumzme** [comment]
![Screen Shot 2020-08-26 at 11 12 48 AM](https://user-images.githubusercontent.com/13012709/91462822-a0288e80-e858-11ea-8870-ccd56108a281.png)

**Comment by mbolotov** [comment]
Hi guys!
I believe I've fixed the connection problem in version 1.6.1, please try it. 
Please also note that 1.6 version brings support for running Cucumber tests from IDE.

**Comment by mbolotov** [comment]
closing as fixed
