### ISSUE TITLE
Plugin fails to select the page to connect

### ISSUE THREAD

**Issue by srosato** [mbolotov/intellij-cypress#14]
Well I am thinking it is possibly related to TypeScript. I have purchased a PRO subscription. I have a cypress setup and my project is written in TypeScript. When I run tests it works well, but when I want to debug them the browser crashes with `cannot find page about:blank to connect`, 

Here is a short screencast to show what is working and what is not, along with the configuration I used on YouTube here: https://youtu.be/SHAf8msE8mU (unlisted).

Tested on Cypress version 4.5.0. I realized my version was outdated, so I upgraded to 5.1.0 and the same thing happens.

Would TypeScript be the possible culprit? Also is it supported by this plugin?

**Comment by mbolotov** [comment]
Hi @srosato!
No, I don't think TypeScript itself can prevent debugging. I was able to debug many different projects with TS. 
I actually see "cannot find page" problem sometimes, but not often (roughly, 1 per 10-20 launches). 
If you run into the problem it stably, I would like to look into your project. Is it possible to share it with me somehow?

Also, you may try to disable automatic page selection as described here:
https://github.com/mbolotov/intellij-cypress/issues/13#issuecomment-675302272

I also will try to make the selection logic more robust and stable.

**Comment by mbolotov** [comment]
Hi @srosato!
Please try it on 1.6.1 version, it should be fixed

**Comment by mbolotov** [comment]
closing as fixed
