### ISSUE TITLE
Test framework quick unexpectedly

### ISSUE THREAD

**Issue by bdox** [mbolotov/intellij-cypress#15]
**Env**
webstorm@2020.2.1
cypress-intellij-reporter@0.0.4
Cypress Support@1.3.0
cypress@5.1.0

Tests run and and all pass, but at the end of the run it prints `Process finished with exit code 0` in the execution console but webstorm does not show the results and shows the message `Test framework quick unexpectedly` in the results pane.

**Comment by mbolotov** [comment]
Hi @bdox!
Are you still experience the problem?
If yes, could you share your project with me to find out what's going wrong?

**Comment by mbolotov** [comment]
Closing this as unreproducible. 
Please fell free to reopen if you have more information.
