### ISSUE TITLE
debugger fails to stop at breaking point

### ISSUE THREAD

**Issue by kokaruk** [mbolotov/intellij-cypress#16]
On Cypress Pro

Keep getting error:

Opening `/dev/tty` failed (6): Device not configured
tput: No value for $TERM and no -T specified

![image](https://user-images.githubusercontent.com/9955277/92880117-06b0cd80-f451-11ea-9f8d-ee700dea2aea.png)

**Comment by mbolotov** [comment]
Hi @kokaruk, 
Please look into #11, there was the same issue

**Comment by mbolotov** [comment]
Hi @kokaruk, 
Please look into #11, there was the same issue

**Comment by mbolotov** [comment]
Hi @kokaruk, 
Please look into #11, there was the same issue

**Comment by mbolotov** [comment]
Hi @kokaruk, 
Please look into #11, there was the same issue

**Comment by kokaruk** [comment]
Debugger runs on first pass and behaves as expected at break point but on the second run it fails, getting "Test framework quit unexpectedly"

**Comment by mbolotov** [comment]
I have no clues what could be wrong. 
Could you record a video to show the problem?
Could you check if it’s reproducible on other machine/os?

**Comment by mbolotov** [comment]
I have no clues what could be wrong. 
Could you record a video to show the problem?
Could you check if it’s reproducible on other machine/os?

**Comment by mbolotov** [comment]
Hi @kokaruk,
Please try it on 1.6.1 version, it should be fixed

**Comment by kokaruk** [comment]
@mbolotov thanks for the update. It's 9PM here in Australia, I'll check tomorrow morning first thing.

**Comment by kokaruk** [comment]
Hi @mbolotov works a treat. Thank you. 

Отлично сделано :)
