### ISSUE TITLE
cypress-support-pro plugin causes custom command warnings

### ISSUE THREAD

**Issue by ponienchen** [mbolotov/intellij-cypress#20]
I am using intelliJ Ultimate IDE.

I have custom commands in **support/commands.js** and their type definitions defined in **support/index.d.ts**

When I enable the plugin, my test files start to complain about my custom commands: "**Method Expression is not of Function type**".
And if I use command+B to view custom command usages, it will be excluded from the search results, making it quite inconvenient for me.

As soon as I disable the plugin, the warning is gone and everything goes back to normal.
I think it is caused by the plugin's auto completion support: "_Auto completion and navigation for aliases references, fixtures and custom commands (PRO version only)_"

Could you please get it fixed ?

**Comment by ponienchen** [comment]
Thanks for your reply.

My ultimate version is 
IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50

Sample command: 
```
Cypress.Commands.add("login", (email, password) => {
    console.log(password);
});
```

using the command:
```
cy.login('abcdefg');
```

Warning message:

![Screen Shot 2020-10-01 at 9 30 52 AM](https://user-images.githubusercontent.com/4860256/94837241-dc578d80-03c8-11eb-927a-9fd4de6e8ba6.png)

**Comment by mbolotov** [comment]
Oh, it seems I'm starting to understand the problem.
You have your code in a JS file, right?
Some background at the plugin side: plugin make special efforts on supporting custom commands for JS tests only since in TS case, it's easy to get the definitions down and have all the code completion and navigation features done by the IDE itself.
So I've actually never tried tests in JS with TS definitions. I'll look into this case.
BTW, why don't you use TS everywhere?

**Comment by ponienchen** [comment]
I didn't have particular needs to use TS everywhere else, except for type definition for making auto-completion work for custom commands.

I was following this example to set up the auto-completion.
```
https://docs.cypress.io/guides/tooling/intelligent-code-completion.html#Set-up-in-your-Dev-Environment

https://github.com/cypress-io/cypress-example-todomvc#custom-commands
```

**Comment by mbolotov** [comment]
Okay, I'll probably disable direct custom command resolving in plugin in the favor of TS definitions. I'll also probably add some support to make it easier to work with the definitions file.

**Comment by ponienchen** [comment]
Thank you so much for your help!

**Comment by mbolotov** [comment]
Hi @ponienchen!
In version 1.6.1, I've added the ability to disable custom command support (as well as alias and fixture ones) via the `Registry`. You can call it by `Tools -> Internal Actions -> Registry` menu item:
![image](https://user-images.githubusercontent.com/19785715/95064783-e51dcb80-0708-11eb-82da-deccc5f7e244.png)

So closing this issue now.

**Comment by ponienchen** [comment]
Than you for the update.
It is working for me.
