### ISSUE TITLE
Trial mode works weird - "license is expired" message right after plugin installation

### ISSUE THREAD

**Issue by YevgenShem** [mbolotov/intellij-cypress#27]
In WebStorm, I got the "Cypress-Pro plugin license is expired. Plugin has been discharged." message right after the https://plugins.jetbrains.com/plugin/13987-cypress-support-pro plugin installation. I've never installed the plugin before today

[stacktrace.txt](https://github.com/mbolotov/intellij-cypress/files/5480601/stacktrace.txt)

**Comment by mbolotov** [comment]
Hi @YevgenShem!
Did you restart the IDE after plugin installation?
It might be some issues of the dynamic plugin reloading. 
If this does not help, I don't know what could be done. Licence validation logic is performed by the IntelliJ platform code, so I can't help there.

**Comment by YevgenShem** [comment]
Hi @mbolotov, it seems that not regular WebStorm restart after a plugin installation (usually WebStorm proposes restart to finish a plugin installation), but "Invalidate and Restart" option helped. After that, the "License Activation" window appeared with "Activate" and "Evaluate for free" options. So for now the evaluations started, thanks!
