### ISSUE TITLE
Cypress runner hijacking other test runners

### ISSUE THREAD

**Issue by fearhq** [mbolotov/intellij-cypress#28]
It seems as if the cypress runner is hijacking other test runners, regardless of what I set as the cypress project base.
Is this behaviour intended? How do I limit cypress runner to only my e2e tests? I am also using the jest runner in a Vue.js project. Sometimes my jest runner is available, but I am unsure when

**Comment by mbolotov** [comment]
Hi @fearhq!
Unfortunately, there is no way to limit runner in the current version. 
I'll will add more complex logic for that in the next version.

**Comment by mbolotov** [comment]
hi @fearhq!
could you provide/describe a case when the jest runner is never available?
I have added some fixes to the plugin and now I would like verify it works as expected.

**Comment by fearhq** [comment]
I have a vue project, jest configured under /tests/unit, and cypress under /tests/e2e
Here are my jest and cypress configurations
[config.zip](https://github.com/mbolotov/intellij-cypress/files/5502805/config.zip)

**Comment by mbolotov** [comment]
hi @fearhq!
Could you check if this issue was fixed in the 1.6.2 version?

**Comment by fearhq** [comment]
Seems to have fixed the issue! If it persists, I will let you know. Thank you very much!
