### ISSUE TITLE
Support for WebStorm 2021.1 EAP

### ISSUE THREAD

**Issue by fearhq** [mbolotov/intellij-cypress#36]
Is it possible to update the pro plugin to support WebStorm 2021.1 EAP?

**Comment by mbolotov** [comment]
hi @fearhq !
Yes, I think it will not be a problem. I'll do it in a couple of days.

**Comment by mbolotov** [comment]
Hi @fearhq!
Please try the 1.8 version of plugin

**Comment by fearhq** [comment]
Works perfectly!
