### ISSUE TITLE
Test run shows as successful but it doesn't run the tests

### ISSUE THREAD

**Issue by Shpota** [mbolotov/intellij-cypress#38]
If I run a test suite it completes in 12 seconds and reports as successful. In fact, it doesn't start the suite at all. My tests take minutes to complete, and even if intentionally break them, the test run is green.

**Comment by mbolotov** [comment]
hi @Shpota!
Could you please provide any reproducible sample? Otherwise I unable to investigate the problem

**Comment by Shpota** [comment]
I tried to reproduce on a test project, but it worked well. I am not sure what causes the issue in my original code base, but I'll experiment more.

**Comment by mbolotov** [comment]
Hello, Sasha!
Have you seen problems since then?

**Comment by Shpota** [comment]
Hi Mikhail,

I have seen the issue. But now after I revisited it once again and once again couldn't reproduce it on a test project, I am pretty sure the issue is not related to the plugin.

I noticed that the suite I had issues with had a specific structure with nested `it()` calls. Something like this:
```
it("Verify page title", () => {
    cy.visit("/");
    cy.title().should("eq", "My Title");
    const vehicles = ["car", "bike", "scooter"];
    vehicles.map(vehicle => {
        it(`This should always fail ${vehicle}`, () => {
            cy.visit("/");
            cy.title().should("eq", vehicle);
        });
    });
});
```
This code doesn't fail no matter if I run it via the plugin or with cli. I am not sure if this really could work in my original project (the code has changed since then).

I find it weird though that this code doesn't fail. I am not an expert in front-end development, do you maybe know why the nested `it()` calls don't work?

Thank you and I am sorry for the false alarm :)
