### ISSUE TITLE
.only is inserted in the wrong place making it impossible to run tests

### ISSUE THREAD

**Issue by JeSuis** [mbolotov/intellij-cypress#41]
`.only` should be inserted after `describe`, it looks like it doesn't play well if there are multiple brackets.
It also will not remove `.only` after execution fails.

The same probably happens with any keyword in the same situation.

![image](https://user-images.githubusercontent.com/2349269/111504605-39988e80-871e-11eb-8c4b-384324faff76.png)

**Comment by mbolotov** [comment]
fixed in 1.4.1 base version and in 2.0.1 Pro version
