### ISSUE TITLE
Feature request: custom command intellisense?

### ISSUE THREAD

**Issue by fearhq** [mbolotov/intellij-cypress#42]
I have noticed that custom command autocomplete works, but intellisense doesn't (highlighted as invalid/method expression not a function)
Is it possible to enable intellisense for these cases? If not, is there a workaround?

Thank you for your hard work on this plugin!

**Comment by mbolotov** [comment]
I suppose you are using custom commands in plain JS with no type definitions for the commands, right?
So a workaround (better to say the right way) is to define types for you commands. See [here](https://docs.cypress.io/guides/tooling/typescript-support.html#Types-for-custom-commands) for details. 
Is this approach acceptable for you?

**Comment by mbolotov** [comment]
Hey, @fearhq!
Do you have a chance to try using type definitions?

**Comment by fearhq** [comment]
Hello @mbolotov !
I have attempted to add type definitions inside my project, but have gotten a bit confused, since my project is not a typescript project. I have attempted to create type definitions, but cannot get them to load

**Comment by mbolotov** [comment]
you could try the 2.0 version of the plugin. It can automate generation of type definitions for your commands.
see here: https://youtu.be/nCIgdCcPamM

**Comment by mbolotov** [comment]
closing this as IDE supports this feature via TypeScript definitions, see [https://docs.cypress.io/guides/tooling/typescript-support.html#Types-for-custom-commands](here)
And the plugin make it easy to use this feature: https://youtu.be/nCIgdCcPamM
