### ISSUE TITLE
No remote node interpreter?

### ISSUE THREAD

**Issue by ddnexus** [mbolotov/intellij-cypress#43]
With JetBrains Node.js and Note.js remote interpreter, I can use docker. Couldn't the cypress plugin use the same remote interpreter?

**Comment by kut** [comment]
Agreed, without the remote interpreter (from the Node.js Remove Interpreter plugin, giving the "Add remote..." option to the interpreters), I can't use this library as our Node.js is sitting inside a docker container.

**Comment by mbolotov** [comment]
Okay, I will take a look at this

**Comment by mbolotov** [comment]
fixed in 3.4 version
