### ISSUE TITLE
[Issue] cy.wait autocompletion & syntax highlighting not working w/ array

### ISSUE THREAD

**Issue by tianalemesle** [mbolotov/intellij-cypress#47]
```js
cy.wait(['@getUsers', '@getActivities', '@getComments'])
```

https://docs.cypress.io/api/commands/wait#You-can-pass-an-array-of-aliases-that-will-be-waited-on-before-resolving

**Comment by mikebolotov** [comment]
@tianalemesle , thanks for the report!
I will try to fix this in the next plugin release.

**Comment by tianalemesle** [comment]
Thanks !

**Comment by mbolotov** [comment]
should be fixed in [2.2.0](https://plugins.jetbrains.com/plugin/13987-cypress-support-pro/versions/stable/124950)

**Comment by tianalemesle** [comment]
It is, thanks !
