### ISSUE TITLE
Cypress cucumber files do not run scenarios with cypress runner when using gutter icons

### ISSUE THREAD

**Issue by rhpkegel** [mbolotov/intellij-cypress#48]
![image](https://user-images.githubusercontent.com/78787971/122524395-5c398c80-d018-11eb-9da3-0a495dc481ef.png)
When using the gutter runner on the left side of a gherkin file, Intellij does not use cypress to run our features, instead running with cucumber, cucumber-js or behave. The runner works normally when you select run from the file context menu. We've been experiencing this for a while now, but it used to work. I believe it might have something to do with the update to 1.6.2? Are we doing something wrong? Do we need to configure the gutter icons to use cypress somehow?

**Comment by mbolotov** [comment]
Hi @rhpkegel,
Thanks for reporting this issue!
This is indeed a problem inside the plugin (or platform) logic. I will try to fix it within the nearest plugin release. 
Unfortunately, it seems there is no workaround for this issue.

**Comment by mbolotov** [comment]
should be fixed in [2.2.0](https://plugins.jetbrains.com/plugin/13987-cypress-support-pro/versions/stable/124950)
