### ISSUE TITLE
Program run arguments escapes double quotes

### ISSUE THREAD

**Issue by rhpkegel** [mbolotov/intellij-cypress#52]
Our setup adds a run argument with `-e TAGS="not @disabled-bugged OR @not-implemented"`. The double quotes in these are now incorrectly escaped, as the final command now includes `-e TAGS=\"not @disabled-bugged OR @not-implemented\"` causing the argument not to work. I believe this is a recent issue, this used to work fine. Is there a way to prevent these escape characters from being added?

**Comment by mbolotov** [comment]
Hi @rhpkegel!
I don't remember changing something like this in recent versions. It seems there is no workaround currently. 
I will look into this problem later today.

**Comment by mbolotov** [comment]
@rhpkegel 
I think I've fixed the problem.
Could you try this snapshot bundle?  
[Cypress Support Pro-2.3.0-SNAPSHOT.zip](https://github.com/mbolotov/intellij-cypress/files/6869275/Cypress.Support.Pro-2.3.0-SNAPSHOT.zip)

**Comment by rhpkegel** [comment]
unfortunately the problem seems to persist. My program arguments: 
![image](https://user-images.githubusercontent.com/78787971/126950507-be5795a5-9076-4d96-bcb7-de6951e81982.png)
The output command (some user specific things whited out): 
![output](https://user-images.githubusercontent.com/78787971/126950886-3b45d368-224c-410b-9f66-0dd97665695f.png)
and the currently running version: 
![image](https://user-images.githubusercontent.com/78787971/126950987-bf263cbf-a932-416f-8e4d-3bf6a35f163b.png)

**Comment by mbolotov** [comment]
Could you please try this version:
[Cypress Support Pro-2.3.0-SNAPSHOT-2.zip](https://github.com/mbolotov/intellij-cypress/files/6877703/Cypress.Support.Pro-2.3.0-SNAPSHOT-2.zip)

> I just noticed that it did throw a few exceptions
Thanks, I've added a fix for that as well.

**Comment by rhpkegel** [comment]
Wonderful! This seems to fix my issue. On the subject of unescaped characters however, my colleague did have a similar problem: she cannot run tests with the Cypress runner at all, because her project is located in a directory with a space character, like so: `C:\Users\Jane Doe\projects\myProject\src\main\frontend\cypress\integration/**/*`. The plugin then fails to load the reporter, like so: 

`Warning: It looks like you're passing --spec a space-separated list of arguments:
"C:\Users\Jane Doe\projects\myProject\src\main\frontend\cypress\integration/**/*"
This will work, but it's not recommended.
If you are trying to pass multiple arguments, separate them with commas instead:
  cypress run --spec arg1,arg2,arg3
The most common cause of this warning is using an unescaped glob pattern. If you are
trying to pass a glob pattern, escape it using quotes:
  cypress run --spec "**/*.spec.js"
Could not load reporter by name: C:\Users\Jane
We searched for the reporter in these paths:
- C:\Users\Jane
The error we received was:
Cannot find module 'C:\Users\Jane'`

Would you like me to create a separate issue for this?

**Comment by mbolotov** [comment]
Yes, a separate issue would be nice.

**Comment by mbolotov** [comment]
fixed in 2.3.0 version
