### ISSUE TITLE
Cypress runner will not run when activated with a path containing whitespaces

### ISSUE THREAD

**Issue by rhpkegel** [mbolotov/intellij-cypress#53]
we cannot run tests with the Cypress runner at all on one of our machines, because the project is located in a directory with a space character, like so: C:\Users\Jane Doe\projects\myProject\src\main\frontend\cypress\integration/**/*. The plugin then fails to load the reporter, like so:

```
Warning: It looks like you're passing --spec a space-separated list of arguments:
"C:\Users\Jane Doe\projects\myProject\src\main\frontend\cypress\integration/**/*"
This will work, but it's not recommended.
If you are trying to pass multiple arguments, separate them with commas instead:
  cypress run --spec arg1,arg2,arg3
The most common cause of this warning is using an unescaped glob pattern. If you are
trying to pass a glob pattern, escape it using quotes:
  cypress run --spec "**/*.spec.js"
Could not load reporter by name: C:\Users\Jane
We searched for the reporter in these paths:
- C:\Users\Jane
The error we received was:
Cannot find module 'C:\Users\Jane'
```

For completeness' sake, the command that is run is as follows:
`
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npx-cli.js" cypress run -b chrome --headless -e TAGS=\"not (@nog-te-implementeren or @niet-runnen-ivm-bug)\" --reporter "C:\Users\Jane Doe\AppData\Local\Temp\intellij-cypress-reporter9985614208215620979.js" --spec "C:\Users\Jane Doe\projects\myProject\src\main\frontend\cypress\integration/**/*"`

**Comment by mbolotov** [comment]
It a bit hard to create a separate user with a space in the name for me.

So I just tried to run the command with spaces in other places. And it worked okay for me.
The command was as follows:
`"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npx-cli.js" cypress run --reporter "C:\Users\mbolotov\AppData\Local\Temp\my dir11585968697581366181\intellij-cypress-reporter1427337492072983935.js" --spec "C:/work/t/new folder/cypress-starter-kit/tests/cypress/integration/foo bar/sample-test.js"`

As a workaround, you could try using the [old approach ](https://github.com/mbolotov/intellij-cypress/tree/3a0440135b6a93f265117512ddd74b85b7ec6bc8#cypress-project-setup) with the intellij-cypress-reporter installed as a project dependency.

**Comment by mbolotov** [comment]
@rhpkegel, have you had a chance to try the workaround?

**Comment by rhpkegel** [comment]
@mbolotov Hey! Sorry, I didn't get your message, github's interface is a mystery to me sometimes. I'm afraid my colleague that suffers from this issue has not done anything with cypress lately, so I've not had the chance to test this. Apologies for the inconvenience!
