### ISSUE TITLE
No watch mode

### ISSUE THREAD

**Issue by tvanc** [mbolotov/intellij-cypress#63]
One thing I enjoy about using Cypress via `yarn cypress open` is that the tests re-run automatically when the source or test file changes.

With Jest I can modify my run configuration to pass `--watch`, which does the same.

There doesn't seem to be any way using this plugin to enable a watch mode to cause Cypress to re-run tests automatically when test or source files change.

Thank you for the plugin. I just started using the pro version today.

**Comment by mbolotov** [comment]
Hi @tvanc!
how do you start tests via plugin? do you use the `interactive` mode?
![image](https://user-images.githubusercontent.com/19785715/133965469-5a208822-fc6e-4b68-b2ee-6d7f7bc7318f.png)

This mode will run Cypress using the `open` command as you do when running it via yarn.

**Comment by tvanc** [comment]
Selecting _Interactive mode_ does mimic the `open` command as you say. I would love to be able to have a watch mode that works with _Headed_ or _Headless_. It can be really handy to debug using the JetBrains debug panel instead of the browser dev tools. Right now if I want to debug with a watch mode, I can only use the browser dev tools.

Some of my tests are unit tests that don't necessarily need a complete browser context. I could use Jest for those if I need to write a lot more of them, and Cypress with this plugin for the ones where `jsdom` is insufficient.
That would get me 80% of the way towards the testing experience I'm looking for.

**Comment by mbolotov** [comment]
Do you mean that debug via IntelliJ is not working in Interactive mode? 
Let me double check this, but it should work and I saw it working some time ago.
As for the watch mode within `run` mode, it's [a Cypress limitation itself](https://github.com/cypress-io/cypress/issues/3665).

**Comment by tvanc** [comment]
Thanks for the info. I didn't know about the limitation with watch mode within run mode in Cypress.

I just tested and I wasn't able to debug via intellij in interactive mode. In interactive mode, I have to debug using the Chrome dev tools.

**Comment by mbolotov** [comment]
If you are still not able to debug via intellij in interactive mode, please provide more information to reproduce the problem as I see it working.

**Comment by tvanc** [comment]
I just had it happen one more time... but not again after I restarted the script in debug mode and reset the breakpoints.

That's good to me 😁

Thank you for the plugin!
