### ISSUE TITLE
Add support for running component tests (base version)

### ISSUE THREAD

**Issue by freezer278** [mbolotov/intellij-cypress#71]
Currently plugin supports only running e2e tests with following cypress command: cypress run
I need support for component tests that require the following cypress command to run: cypress run-ct

You can read more about cypress component tests [here](https://docs.cypress.io/guides/component-testing/introduction#What-is-Component-Testing)

**Comment by mbolotov** [comment]
Hi @freezer278!
You might know that the [Cypress Pro](https://plugins.jetbrains.com/plugin/13987-cypress-support-pro) plugin already supports running component tests.
I currently have no resources to add this functionality to the base version. Feel free to add a pull request for this to the base version.

**Comment by mbolotov** [comment]
`Cypresso` plugin version `1.8.0` is able to run component tests
