### ISSUE TITLE
Cypress plugin seems to override Webstorm run/debug config 

### ISSUE THREAD

**Issue by vanch3d** [mbolotov/intellij-cypress#73]
When I'm right-clicking on a javascript file in the project menu, I can choose to run or debug it, possibly modifying the run configuration: 

![react-viewranger 06_12_2021 10_47_30 (2)](https://user-images.githubusercontent.com/2743481/144833154-3466853b-61b7-416c-b4a1-39d3c6f161dc.png)

By default, the file is recognised as a .JS and gives me the node configuration: 

![react-viewranger – cypress json 06_12_2021 10_34_49](https://user-images.githubusercontent.com/2743481/144833268-0cc52978-1d7d-4639-9352-b9264ec83e97.png)

But when the Cypress plugin is activated, **every** JS files is now offering a Cypress configuration dialog, regardless of whether  they are a test file (no `.spec.` in file name) or even just in the `cypress` directory 

![react-viewranger – cypress json 06_12_2021 10_36_04](https://user-images.githubusercontent.com/2743481/144833466-aea8ded6-862a-4497-814d-c872a4742ef0.png)

---
```
WebStorm 2021.3
Build #WS-213.5744.224, built on November 27, 2021
Licensed to XXXXXXX
Subscription is active until XXXXXX
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    net.sjrx.intellij.plugins.systemdunitfiles (0.3.4)
    com.jetbrains.plugins.ini4idea (213.5744.190)
    com.intellij.apacheConfig (213.5744.190)
    mobi.hsz.idea.gitignore (4.3.0)
    com.eny.i18n (2.6.1)
    me.mbolotov.cypress (1.4.2)
    ru.adelf.idea.dotenv (2021.3.0.213)
    DBN (3.2.6411.0)
```

**Comment by vanch3d** [comment]
To add to the comment above, `Cypress` itself runs properly. My alternative is now to edit manually the run config by explicitly choosing the target. I haven't found a workaround, short of disactivating the plugin

**Comment by mbolotov** [comment]
Starting 1.8.0 version, the plugin will override a run configuration only for the files that are selected as cypress tests by the Cypress configuration only. 
So it will create a Node run configuration for something like `index.js`.
