### ISSUE TITLE
"Run Cucumber tests from IDE" doesn't work

### ISSUE THREAD

**Issue by DannyEnsink** [mbolotov/intellij-cypress#76]
When clicking next to a test in the sidebar on the green arrows and click Run 'Name of the Test' it always fails using Cypress Support Pro:
![image](https://user-images.githubusercontent.com/8476848/148565102-da038c1e-49b7-43b7-8b83-e315dae662ad.png)
![image](https://user-images.githubusercontent.com/8476848/148565274-b398d1b6-94bd-4640-89d4-7d168c43b553.png)

It seems it doesn't create a configuration type of Cypress but it creates a configuration type of Cucumber.js:
![image](https://user-images.githubusercontent.com/8476848/148565913-ef724354-ec75-4b8c-bee7-164d920f6fc5.png)

Do you know how to solve this issue?

**Comment by mbolotov** [comment]
Hi @DannyEnsink!
Please ensure your feature file is located under the Cypress `integration` folder as it defined by your Cypress configuration file (which is `cypress/integration` by default). 
The plugin shows the run gutters for the files inside the integration folder only.

**Comment by DannyEnsink** [comment]
Hi @mbolotov !
All `.feature` files are already located under the Cypress `integration` folder. Do you have any other ideas why this might be happening?

**Comment by mbolotov** [comment]
Unfortunately, no.
I need a sample project to debug the problem. Could you provide any?

**Comment by DannyEnsink** [comment]
I found a fix, which ended up being rather simple.
Inside Rider IDE go to File > Settings... > Languages & Frameworks > Cypress > Cypress config file path.
By default this field is empty and the IDE is supposed to look for the cypress.json file by itself, but in our case it seems to not being able to find it (although the IDE isn't saying it cannot find it).

So the solution ended up being to put the path to the cypress.json file there and everything started to work.
