### ISSUE TITLE
I upgraded to 2.6.0 pro and debugging stopped working 

### ISSUE THREAD

**Issue by francisu** [mbolotov/intellij-cypress#78]
I also moved to react-scripts
<img width="660" alt="Screen Shot 2022-01-24 at 00 47 08" src="https://user-images.githubusercontent.com/944949/150750334-f653c495-d7af-4d62-9ce3-b938ca2adfdf.png">
<img width="663" alt="Screen Shot 2022-01-24 at 00 47 18" src="https://user-images.githubusercontent.com/944949/150750344-aac91d14-e0fb-463e-a455-044c1b97ed0b.png">
 (and webpack) 5, so maybe this has to do with it.

Below  is the console output (note it's not showing the debugger starting)

Attached are my configurations (I'm using component testing). 

WIth the older version (I forget which version exactly) and react-scripts 4 (webpack 4) The debugger started properly and I was able to set breakpoints.

/Users/francis/.nvm/versions/node/v14.17.3/bin/node /usr/local/Cellar/yarn/1.22.4/libexec/bin/yarn.js run cypress open-ct -b electron --config testFiles=**/action.spec.ts
[81636:0124/003830.580537:ERROR:node_bindings.cc(276)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[81636:0124/003830.580567:ERROR:node_bindings.cc(276)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.

DevTools listening on ws://127.0.0.1:53952/devtools/browser/ee7eff8a-1590-4975-b4ec-873ecd99c854
[@cypress/webpack-dev-server]: removing HtmlWebpackPlugin from configuration.
[0mGET /__/ [32m200 [0m48.172 ms - -[0m
[0mGET /__cypress/runner/cypress_runner.css [32m200 [0m8.803 ms - -[0m
[0mGET /__cypress/runner/cypress_runner.js [32m200 [0m86.653 ms - -[0m
[0mGET /__cypress/runner/popper.js.map [33m404 [0m3.845 ms - 136[0m
[0mGET /__/ctChunk-reactdevtools.css [32m200 [0m1.657 ms - 304[0m
[0mGET /__/ctChunk-reactdevtools.a43cc3e83c6757e6cdac.js [32m200 [0m20.730 ms - -[0m
[0mGET /__/vendors~ctChunk-reactdevtools.71f4c4a828a7b7522abe.js [32m200 [0m56.401 ms - -[0m
[0mGET /__cypress/runner/fonts/open-sans-latin-400-normal.woff2 [32m200 [0m15.777 ms - 14380[0m
[0mGET /__cypress/runner/fonts/mulish-latin-400-normal.woff2 [32m200 [0m19.953 ms - 31176[0m
[0mGET /__cypress/runner/fonts/mulish-latin-500-normal.woff2 [32m200 [0m15.403 ms - 31176[0m
[0mGET /__cypress/runner/fonts/fa-solid-900.woff2 [32m200 [0m19.394 ms - 76120[0m
[0mGET /__cypress/iframes//Users/francis/d/IdeaProjects/product/packages/client/src/__tests__/action.spec.ts [0m- [0m- ms - -[0m
[0mGET /__cypress/runner/popper.js.map [33m404 [0m0.443 ms - 136[0m
[0mGET /__cypress/iframes//Users/francis/d/IdeaProjects/product/packages/client/src/__tests__/action.spec.ts [0m- [0m- ms - -[0m
[0mGET /__cypress/runner/popper.js.map [33m404 [0m34.009 ms - 136[0m
assets by path [1m[32mstatic/[39m[22m 50.8 MiB
  assets by path [1m[32mstatic/js/*.js[39m[22m 48.4 MiB
    assets by chunk 45.5 MiB (id hint: vendors) 9 assets
    5 assets
  assets by path [1m[32mstatic/media/[39m[22m 2.45 MiB
    asset [1m[32mstatic/media/.pnp.0cdca609c5f145fd729d.cjs[39m[22m 2.38 MiB [1m[32m[emitted][39m[22m [1m[32m[immutable][39m[22m [from: ../../.pnp.cjs] (auxiliary name: spec-0)
    asset [1m[32mstatic/media/codicon.56dba998166ea5a0ca7f.ttf[39m[22m 66.8 KiB [1m[32m[emitted][39m[22m [1m[32m[immutable][39m[22m [from: ../../.yarn/cache/monaco-editor-patch-86b67e9ffd-8cd6c0b56f.zip/node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.ttf] (auxiliary id hint: vendors)
assets by path [1m[32m*.js[39m[22m 9.9 MiB
  asset [1m[32mts.worker.js[39m[22m 8.37 MiB [1m[32m[emitted][39m[22m 1 related asset
  asset [1m[32mjson.worker.js[39m[22m 795 KiB [1m[32m[emitted][39m[22m 1 related asset
  asset [1m[32meditor.worker.js[39m[22m 531 KiB [1m[32m[emitted][39m[22m 1 related asset
  asset [1m[32mmain.js[39m[22m 242 KiB [1m[32m[emitted][39m[22m (name: main) (id hint: vendors) 1 related asset
asset [1m[32masset-manifest.json[39m[22m 6.86 KiB [1m[32m[emitted][39m[22m
asset [1m[32mindex.html[39m[22m 345 bytes [1m[32m[emitted][39m[22m
orphan modules 1.09 MiB [1m[33m[orphan][39m[22m 585 modules
runtime modules 7.87 KiB 15 modules
modules by path [1m../../.yarn/[39m[22m 36.3 MiB (javascript) 66.8 KiB (asset)
  modules by path [1m../../.yarn/cache/[39m[22m 28.5 MiB (javascript) 66.8 KiB (asset) 2015 modules
  modules by path [1m../../.yarn/__virtual__/[39m[22m 7.57 MiB 1523 modules
  modules by path [1m../../.yarn/unplugged/[39m[22m 193 KiB 283 modules
modules by path [1m./[39m[22m 684 KiB 137 modules
modules by path [1m../universal/[39m[22m 604 KiB 67 modules
modules by path [1mdata:image/[39m[22m 25.4 KiB
  modules by path [1mdata:image/svg+xml,%3csvg xmlns=%27http://www.w3.org/2000/[39m[22m 449 bytes 2 modules
  modules by path [1mdata:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/[39m[22m 619 bytes
    [1mdata:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sJDw4cOCW1/KIAAAAZdEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAHElEQVQI12NggIL/DAz/GdA5/xkY/qPKMDAwAADLZwf5rvm+LQAAAABJRU5ErkJggg==[39m[22m 295 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
    [1mdata:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sJFhQXEbhTg7YAAAAZdEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAMklEQVQI12NkgIIvJ3QXMjAwdDN+OaEbysDA4MPAwNDNwMCwiOHLCd1zX07o6kBVGQEAKBANtobskNMAAAAASUVORK5CYII=[39m[22m 324 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
15 modules
webpack 5.66.0 compiled [1m[32msuccessfully[39m[22m in 104837 ms
[32mNo issues found.[39m
Watchpack Error (initial scan): Error: ENOTDIR: not a directory, scandir '/Users/francis/d/IdeaProjects/product/.pnp.cjs'
[0mGET /__cypress/iframes//Users/francis/d/IdeaProjects/product/packages/client/src/__tests__/action.spec.ts [32m200 [0m15410.877 ms - 345[0m
[0mGET /__/frontend.js.map [33m404 [0m113002.139 ms - -[0m
[0mGET /__/frontend.js.map [33m404 [0m107894.788 ms - -[0m
[0mGET /__cypress/src/main.js [0m- [0m- ms - -[0m
[0mGET /__cypress/runner/popper.js.map [33m404 [0m0.819 ms - 136[0m
assets by status 60.5 MiB [1m[32m[cached][39m[22m 19 assets
assets by path [1m[32m.[39m[22m 249 KiB
  asset [1m[32mmain.js[39m[22m 242 KiB [1m[32m[emitted][39m[22m (name: main) (id hint: vendors) 1 related asset
  asset [1m[32masset-manifest.json[39m[22m 6.86 KiB [1m[32m[emitted][39m[22m
  asset [1m[32mindex.html[39m[22m 345 bytes [1m[32m[emitted][39m[22m
cached modules 38.8 MiB (javascript) 66.8 KiB (asset) [1m[32m[cached][39m[22m 5011 modules
runtime modules 7.87 KiB 15 modules
modules by layer 202 bytes (javascript) 2.38 MiB (asset)
  [1m../universal/ sync[39m[22m 160 bytes [1m[33m[optional][39m[22m [1m[33m[built][39m[22m
  [1m../../.pnp.cjs[39m[22m 42 bytes (javascript) 2.38 MiB (asset) [1m[33m[built][39m[22m
webpack 5.66.0 compiled [1m[32msuccessfully[39m[22m in 7548 ms
[0mGET /__cypress/iframes//Users/francis/d/IdeaProjects/product/packages/client/src/__tests__/action.spec.ts [36m304 [0m331.298 ms - -[0m
[0mGET /__/frontend.js.map [33m404 [0m23281.703 ms - -[0m
[32mNo issues found.[39m
[0mGET /__cypress/src/main.js [32m200 [0m8.217 ms - -[0m
[0mGET /__cypress/src/static/js/cypress_support_index_ts-_yarn_cache_cypress-react-selector-npm-2_3_15-cf41e213da-74c9117680_-230cc9.chunk.js [32m200 [0m6.639 ms - -[0m
[0mGET /__cypress/src/static/js/vendors-_yarn_cache_cypress-react-selector-npm-2_3_15-cf41e213da-74c9117680_zip_node_modules_-e7dcce.chunk.js [32m200 [0m9.466 ms - -[0m
[0mGET /__cypress/src/main.js.map [32m200 [0m9.347 ms - -[0m
[0mGET /__cypress/src/static/js/cypress_support_index_ts-_yarn_cache_cypress-react-selector-npm-2_3_15-cf41e213da-74c9117680_-230cc9.chunk.js.map [32m200 [0m165.638 ms - -[0m
[0mGET /__cypress/src/static/js/vendors-_yarn_cache_cypress-react-selector-npm-2_3_15-cf41e213da-74c9117680_zip_node_modules_-e7dcce.chunk.js.map [32m200 [0m160.843 ms - -[0m
[0mGET /__/frontend.js.map [33m404 [0m541.872 ms - -[0m
[0mGET /__cypress/src/static/js/spec-0.chunk.js [32m200 [0m165.881 ms - -[0m
[0mGET /__cypress/src/static/js/spec-0.chunk.js.map [32m200 [0m22.936 ms - -[0m
[0mGET /__cypress/src/static/js/vendors-_yarn___virtual___apollo-client-virtual-12b505e47e_0_cache_apollo-client-npm-3_3_16-f-c983a5.chunk.js [32m200 [0m164.975 ms - -[0m
[0mGET /logger-1.min.js [32m200 [0m600.609 ms - -[0m
[0mGET /__cypress/runner/fonts/fa-regular-400.woff2 [32m200 [0m22.909 ms - 13600[0m
[0mGET /worm-238.snapstrat.com/stackInfo.zip?timestamp=1643013689318 [32m200 [0m241.708 ms - -[0m
[0mGET /__cypress/src/static/js/vendors-_yarn___virtual___apollo-client-virtual-12b505e47e_0_cache_apollo-client-npm-3_3_16-f-c983a5.chunk.js.map [32m200 [0m328.560 ms - -[0m
[0mOPTIONS / [32m200 [0m266.250 ms - -[0m
[0mPOST / [32m200 [0m558.676 ms - -[0m
[0mOPTIONS /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m201.491 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m4523.018 ms - -[0m
[0mPOST / [32m200 [0m43.576 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m129.297 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m240.034 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m112.599 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m126.762 ms - -[0m
[0mPOST / [32m200 [0m43.123 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m157.044 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m263.789 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m126.889 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m78.056 ms - -[0m
[0mPOST / [32m200 [0m41.312 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m168.865 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m212.901 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m111.988 ms - -[0m
[0mGET /worm-238.snapstrat.com/stackInfo.zip?timestamp=1643013724923 [32m200 [0m168.660 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m2408.922 ms - -[0m
[0mPOST / [32m200 [0m40.897 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m139.005 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m194.137 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m55.135 ms - -[0m
[0mPOST /2015-03-31/functions/worm-238-ah/invocations [32m200 [0m142.474 ms - -[0m

**Comment by francisu** [comment]
Thanks for your super fast response. It's showing the debugger is connected in the debugger tab. However, the breakpoints don't have a little checkmark in them. I tried the "debugger" statement, and the browser hits the statement and pauses, but the IDE does not hit the breakpoint (it still shows as running).

Looking forward to what to try next!

**Comment by mbolotov** [comment]
breakpoints are usually not hit when there is a problem with source maps. 
please check if they are generated correctly in your project.

**Comment by francisu** [comment]
OK, I turned the source maps on, and the browser can see the source and stops at the breakpoint, but the IDE does not see the breakpoint nor stop. Is there some setting in the IDE that tells it where to find the source map?

<img width="1861" alt="Screen Shot 2022-01-24 at 15 48 38" src="https://user-images.githubusercontent.com/944949/150884302-5dd70304-b6e0-40e1-93f0-acb08f7b60e2.png">

**Comment by mbolotov** [comment]
you could check what the `Scripts` tab shows:
![image](https://user-images.githubusercontent.com/19785715/150964289-fdf5146e-a371-4edc-af7d-b51c84df47eb.png)
Do you see your test file there? Does `Open Source` menu action bring your to the test file?

**Comment by francisu** [comment]
Here is my scripts tab. Looks completely different.

<img width="543" alt="Screen Shot 2022-01-25 at 08 54 17" src="https://user-images.githubusercontent.com/944949/151022417-c3d38cd1-d15e-4cf2-a36b-d7f4d310c55e.png">

**Comment by mbolotov** [comment]
oh, I didn't pay enough attention that you are using component testing.
let me check this

**Comment by francisu** [comment]
> oh, I didn't pay enough attention that you are using component testing. let me check this

Any ideas?

**Comment by mbolotov** [comment]
If that sample works for you as well, then I suppose I need to get your project to reproduce the issue. Is that possible?

**Comment by mbolotov** [comment]
Okay, I will try

**Comment by francisu** [comment]
I think the issue has to do with the use of webpack 5. It might be something in my webpack config as. I have some customizations. And what I'm doing is the upgrade from 4 to 5.

**Comment by mbolotov** [comment]
It works okay for me with react scripts 5.0.0.
Breakpoints are hit.
![image](https://user-images.githubusercontent.com/19785715/151767826-c5941f3a-1539-4b6c-b4c8-8c582d01c0aa.png)

Here is my final package.json:
```{
  "name": "cypress-react-template",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "lodash": "^4.17.21",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "^5.0.0",
    "webpack": "^5.67.0",
    "typescript": "^4.2.4",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@cypress/code-coverage": "^3.9.4",
    "@cypress/react": "^5.12.1",
    "@cypress/webpack-dev-server": "^1.3.0",
    "@types/lodash": "^4.14.168",
    "babel-plugin-istanbul": "^6.0.0",
    "cypress": "^9.3.1",
    "cypress-react-selector": "^2.3.7",
    "html-webpack-plugin": "4"
  }
}
```
Could you please try the [cypress-react-template example](https://github.com/lmiller1990/cypress-react-template) as well?
