### ISSUE TITLE
Feature idea: Make opening a screenshot available in the test result list

### ISSUE THREAD

**Issue by pszalanski** [mbolotov/intellij-cypress#8]
I just installed your extension yesterday and love it! ❤️ Thank you for this plugin.

However, one thing would make my testing feedback loop a little more efficient. I would like to access the screenshot of a particular failed run right from the test result list. An entry in the context menu would be nice, or some sort of button in the test list.

Do you think that's doable?

**Comment by mbolotov** [comment]
hi @pszalanski!
Thanks for you idea, it looks great. 
I took a brief view into the code and I think this is doable. 

Just one question. Cypress can store multiple screenshot for a single test (e.g. generated by the `cy.screenshot()` command or something remaining from previous runs) 
Do we want to display the latest one in this case?

**Comment by pszalanski** [comment]
How about a list? Or the latest screenshot is also a nice idea.

**Comment by mbolotov** [comment]
this feature is available now in 1.3 (base) and 1.4 (pro) plugin versions.

**Comment by pszalanski** [comment]
Thank you! It works perfectly 😄

**Comment by mbolotov** [comment]
It's no trouble. 
Just forgot to mention that 'last screenshot/screenshot selection list' behavior can be configured in the test view settings:
![image](https://user-images.githubusercontent.com/19785715/83503868-6c91ce80-a4cc-11ea-9b84-a16c7660ea54.png)
