### ISSUE TITLE
No option to create Cypress configurations from Tests in WebStorm (Pro Only)

### ISSUE THREAD

**Issue by aetherealtech** [mbolotov/intellij-cypress#81]
In the free version of the plugin, a test that has no existing configurations provides a menu when the green "play" button is pressed to select Jest or Cypress.  When I upgraded to Pro, this menu disappeared and Jest is always selected when running a test.  Downgrading back to the free plugin fixes the problem.

**Comment by mbolotov** [comment]
Hi Dan,
The Pro version analysis the Cypress configuration file to check if a test file can be accepted by Cypress. If not, the plugin does not show the green icons. 
Are you sure your test file is under the `integrationFolder` folder as it configured by the `cypress.json`

**Comment by mbolotov** [comment]
Hmm, this is very strange. 
I'm almost every day use the plugin in projects with an empty `cypress.json` and it works okay. 
Is it possible somehow to share your project to reproduce the problem?

**Comment by mendieta** [comment]
Hi @mbolotov i have the same issue with webstorm and the pro version of the plugin, with the free version it works perfectly.

**Comment by mendieta** [comment]
A simple new nextjs project (with) ts and adding cypress 10^ will have the problem. Also if cypress is 10 the runner cant use a single test or test file.

**Comment by mendieta** [comment]
version 3.2

**Comment by mbolotov** [comment]
@mendieta 
could you set FINE log level for the plugin?
![image](https://user-images.githubusercontent.com/19785715/177841458-74c389ce-cfa4-4882-a1c7-a72a0f714041.png)

![image](https://user-images.githubusercontent.com/19785715/177841375-3ad65a50-57af-490d-bc39-1f565264a8a7.png)

After that, please reopen a project with problem, collect the log and send it to me.

Please clear all the sensitive data if you have it in the Cypress configuration files.

**Comment by mbolotov** [comment]
@mendieta 
I found a problem. 
Could you try this bundle with the fix: 
[Cypress Support Pro-3.2.1-EAP.zip](https://github.com/mbolotov/intellij-cypress/files/9076327/Cypress.Support.Pro-3.2.1-EAP.zip)

**Comment by mbolotov** [comment]
should be fixed in 3.2.2

**Comment by ufo22940268** [comment]
Same issue for me. 

I am running the plugin of the latest version 3.3.1. And using the cypress 10 which the configuration file is in typescript and not in json format. So does this plugin support the typescript config file yet? like cypress.config.ts

**Comment by mbolotov** [comment]
Hello Chao!
Please create a separate issue for you problem and provide the details. Especially:

1. your OS 
2. any errors the IDE shows after your change (and save) the cypress configuration file
3. the configuration file content (if possible)
4. any other details that you consider suspicious

**Comment by mbolotov** [comment]
and answering the question: yes, the plugin do support typescript config files
