### ISSUE TITLE
Does not work with node runner in WSL2

### ISSUE THREAD

**Issue by squareloop1** [mbolotov/intellij-cypress#82]
This plugin does not seem to work when using node.js inside WSL2. When trying to run a test from the IDE it is throwing an error complaining it cannot find the npm executable even though it exists (and is working correctly with IDE and other plugins):

```Specify a correct path to an npm or yarn package: no such directory "\home\user\.nvm\versions\node\v16.13.2\bin\npm"```

Maybe related to https://github.com/mbolotov/intellij-cypress/issues/43

**Comment by mbolotov** [comment]
fixed in 3.4 version
