### ISSUE TITLE
Rubymine IDE unable to find specifed test files for Cypress Pro

### ISSUE THREAD

**Issue by larryh** [mbolotov/intellij-cypress#87]
Hi,

I flip back and forth between your regular Cypress Support and Cypress Support Pro plugins.

First things first: Thank you for supplying these plugins for us!!!

I used Cypress Pro awhile back (in Rubymine) and it worked like a charm. A few months ago I switched back down to the regular Cypress Support plugin and that works fine as well.

I upgraded back up to Cypress Pro yesterday and now the IDE keeps telling me that it is unable to find my test files. I have attached 3 screenshots that show that. One even has little red "X"s over my test names in the Run Config dialog box.

The good news is that I can just ignore the warnings and click "Continue anyway" and my tests run fine. And the debugger works as well.

Thanks again!

P.S. Cypress Support Pro 3.0 ; Rubymine 2022.1 ; Ubuntu 21.10

![run_warning](https://user-images.githubusercontent.com/89646/164549880-91fab5ef-d1d0-46d4-9039-20f2e3315f50.png)
![one_test](https://user-images.githubusercontent.com/89646/164549882-6b31892e-fbee-48f4-9968-efeedee4d705.png)
![all_tests](https://user-images.githubusercontent.com/89646/164549883-0c967586-33ed-46eb-be2c-79310f64022f.png)

**Comment by mbolotov** [comment]
Hi Larry,

You can try this plugin bundle:
[Cypress Support Pro-3.1-EAP.zip](https://github.com/mbolotov/intellij-cypress/files/8537526/Cypress.Support.Pro-3.1-EAP.zip)
Download it and [install](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk). It should fix the problem.

**Comment by larryh** [comment]
Worked like a charm! Thanks for providing a fix so quickly!
