### ISSUE TITLE
IntelliJ keeps missing cypress-intellij-reporter

### ISSUE THREAD

**Issue by bschatter** [mbolotov/intellij-cypress#9]
**IDE**: IntelliJ Ultimate 2020.1.1 Build #IU-201.7223.91 
**OS**: Windows 10 Pro latest  
**Plugin**: Cypress-Support Pro
**Plugin-Version**: 1.4.0-2020.1
**License**: Trial
**Intellij-Reporter Version**: 0.0.4

**Project**: Multi-module project with Java + JavaScript
**Remarks**: Cypress is being used with Cucumber.JS

**Problem**
The intellij-cypress plugin keeps reporting that the cypress-intellij-reporter is not installed even though it is visible in the package.json. 
The project root path is also set correctly (both, package.json and cypress.json are located there).

**Error Message**
`Warning: Package 'cypress-intellij-reporter' not found under the Cypress project, test tab view will not be shown. Install the package to watch test execution and results`

**Package.json (part)**
`  "devDependencies": {
    "cypress-intellij-reporter": "0.0.4"
  },`

**Installed and enabled IntelliJ Plugins**
[Find the list on pastebin](https://pastebin.com/tTHdS0u2)

**Comment by mbolotov** [comment]
hi @bschatter!
Thank you for reporting the problem.
A couple of questions:
1. Does plugin really not use the reporter when running a test? (the test tree is not shown in this case)
2. Can you describe the structure of you project? Especially, the location of the node modules folder (where reporter is installed to) relative to the cypress test folder

Or, If it's possible, can provide a reproducible repository/archive of your project?

**Comment by bschatter** [comment]
Hi @mbolotov 

apologies for the late reply but thank you very much for your swift response!

1) No it does not show up at all. When running the run configuration it is not run as a test but as an actual run and therefore no test window shows up.

2) The structure is like this:

|- Root
|--acceptancetests (maven module)
|---src
|----main
|-----javascript
|------node_modules
|------cypress

node_modules and cypress residing on the same level. Within the javascript folder are the cypress.json, package.json etc.

If this does not help you I am happy to try to recreate the project structure and poms and send it to you

**Comment by bschatter** [comment]
One thing that might be interesting: the integration folder is NOT in the cypress folder, rather it is in

**src/test/resources/features**

instead of

src/main/javascript/cypress/integration

**Comment by mbolotov** [comment]
Hi @bschatter 
I think I fixed this problem. 
I'm planning release a version of the Pro plugin with this fix in several days. Please let me know if you need the fix quicker.
