### ISSUE TITLE
Cypress Support Pro 3.0 - unable to find the specified test to run - WebStorm

### ISSUE THREAD

**Issue by kamonson** [mbolotov/intellij-cypress#90]
![image](https://user-images.githubusercontent.com/8751955/165804292-7c6ce7c3-1a57-4d2c-ab86-b6aa8b56fc5a.png)

Pretty straight forward.  Since the release of the version 3.0 Cypress Support Pro plugin, a simple debug run cannot happen.

WebStorm Version: 2022.1
Cypress Suport Pro Version: 3.0

Valid spec file utilizing standard Cypress syntax for tests cypress/integration/projects/projects_spec.js 
With a basic configuration, Interactive mode cypress project location is valid All in directory with the correct directory

Error at the base of the configuration menu:

Error: Unable to find the specified test to run

**Comment by mbolotov** [comment]
hi @kamonson!
yes, this is a known problem. Please look at issue #87.
There is a bundle with the fix as well as workaround described there.
Also, this will be fixed in 3.1 version that is going to be fully available in a couple of days.
