### ISSUE TITLE
Alias not resolving - unresolved alias [ Cypress Support Pro ]

### ISSUE THREAD

**Issue by catbreathx** [mbolotov/intellij-cypress#91]
Hi - 

In this specific scenario, Webstorm is giving a warning of an unresolved alias:

```
 it('can click and navigate to external game page', () => {
    cy.visit('/');

    cy.window().then((window) => {
      cy.stub(window, 'open', url => {
        expect(url).to.contain(CHEAPSHARK_REDIRECTION_URL)
      }).as("gameNewWindow")
    })

    cy.get(elements.dataRows).should(  'have.length.at.least', 5);

    cy.get(`${elements.dataRows}:first-child()`).click();
    cy.get('@gameNewWindow').should("be.called")
  })
```

The line is question is `cy.get('@gameNewWindow').should("be.called")`.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/102924977/170588333-36819c59-0cfe-4323-90d0-705fec97765e.png">

It's previously been defined on the `cy.stub` statement.  Removing the `cy.window().then` command doesn't resolve the issue, either.

The test executes and passes as expected.

Thanks.

**Comment by mbolotov** [comment]
fixed in 3.2 version

**Comment by frm-037** [comment]
I use Cypress Support Pro Version 3.6 and have the same issue.

**Comment by mbolotov** [comment]
@frm-037 
please provide the code snippet
