### ISSUE TITLE
Obsolete object used in config object (cypress 10.0.0 support)

### ISSUE THREAD

**Issue by Eitol** [mbolotov/intellij-cypress#94]
![image](https://user-images.githubusercontent.com/1043061/173628954-a2d1ebb3-bf29-4bc5-be19-f238678064dd.png)

**Comment by palendrance** [comment]
To simplify our setups and to help prevent these incompatibilities in the future, it would be nice if we could just tell the plugin to supply no configuration options, that way cypress just uses the same default config file that it would if you were to run it from the CLI.

Additionally, it would be good if we could specify a specific config file to use, that way we can create separate configurations that use each of the config files that we might use in our build system.

**Comment by mbolotov** [comment]
Hi folks,
Could you try this beta of the plugin with Cypress 10 support. 
Please report issues here if you find any
[Cypress Support Pro-3.2-EAP.zip](https://github.com/mbolotov/intellij-cypress/files/8913057/Cypress.Support.Pro-3.2-EAP.zip)
.

**Comment by larryh** [comment]
I tried it and it worked like a charm - thanks!

**Comment by mbolotov** [comment]
Hi folks!
I'm close to releasing a new version with full Cypress 10 support.
Could you try this bundle
[Cypress Support Pro-3.2-EAP-2.zip](https://github.com/mbolotov/intellij-cypress/files/9034255/Cypress.Support.Pro-3.2-EAP-2.zip)
Now the configuration is evaluated in IDE and the plugin can use it's values to validate paths and make suggestions (the same as it does for Cypress 9 and below).

**Comment by larryh** [comment]
It worked for me. (Cypress 10.1.0; Ubuntu 22.04; Rubymine 2022.1.3)

**Comment by mbolotov** [comment]
Plugin 3.2 version has been released today with full support for Cypress 10
