### ISSUE TITLE
Path selector dialog for the Cypress configuration file shows JSON files only

### ISSUE THREAD

**Issue by OrbisK** [mbolotov/intellij-cypress#98]
Seems like non JSON configs are not supported.

![image](https://user-images.githubusercontent.com/37191683/178680696-e4903d25-ac72-4eb7-bb98-ec8368d902fa.png)

**Comment by mbolotov** [comment]
okay, the path selector dialog indeed shows only *.json files. 
As a workaround, you can type the path manually.

**Comment by mbolotov** [comment]
fixed in 3.2.2
